services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_symfony_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
      - APP_SECRET=${APP_SECRET_PASS}
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:17.4
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      POSTGRES_DB: ${MYSQL_DATABASE}
      POSTGRES_USER: ${PMA_USER}
    ports:
      - "5432:5432"
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "8000:80" # Host port 8000 maps to container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - symfony
    networks:
      - my_network

  mailer:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ server port
      - "15672:15672" # Management web interface
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
