services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\UserContext\:
    resource: '../'
    exclude:
      - '../Domain/Events/'
      - '../Config/'

  App\UserContext\Application\Handlers\CommandHandlers\:
    resource: '../Application/Handlers/CommandHandlers/'
    tags: ['messenger.message_handler']


  App\UserContext\ReadModels\Projections\:
    resource: '../ReadModels/Projections/'
    tags: [ 'messenger.message_handler']
